name: skycalc_ipy

channels:
    - astropy

dependencies:
    - python>=2.7
    - astropy
    - matplotlib
    - numpy
    - sphinx-astropy
    - synphot
    - requests
    - pyyaml

#   - pip:
#       - dependency_from_pip
